spring:
  profiles:
    active: develop

  datasource:
    username: root
    password: root

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      use_sql_comments: true
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect

  flyway:
    baseline-on-migrate: true
    baseline-version: 0


logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.springframework.web: debug

---

spring:
  profiles: develop

  datasource:
    url: jdbc:mysql://seller_lee_database:3306/sl_db?useSSL=false&allowPublicKeyRetrieval=true&autoReconnection=true

---

spring:
  profiles: local

  datasource:
    url: jdbc:mysql://localhost:3306/sl_db?useSSL=false&allowPublicKeyRetrieval=true&autoReconnection=true
