spring:
  profiles:
    active: local

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;IFEXISTS=FALSE;
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
