spring:
  profiles:
    active: local

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.springframework.web: debug

---

spring:
  profiles: local

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
      use_sql_comments: true

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:tcp://localhost/${user.dir}/test;IFEXISTS=FALSE;
    username: sa
    password:
    driver-class-name: org.h2.Driver
